import Head from 'next/head'
import { BsFillMoonStarsFill } from "react-icons/bs"
import { AiFillTwitterCircle, AiFillYoutube, AiFillLinkedin } from "react-icons/ai"
import Image from 'next/image'
import deved from "../public/dev-ed-wave.png"
import design from "../public/design.png"
import code from "../public/code.png"
import consulting from "../public/consulting.png"
import web1 from "../public/web1.png"
import web2 from "../public/web2.png"
import web3 from "../public/web3.png"
import web4 from "../public/web4.png"
import web5 from "../public/web5.png"
import web6 from "../public/web6.png"
import { useState } from 'react'

export default function Home() {

    const [darkMode, setDarkMode] = useState(false)

    return (
        <div className={darkMode ? "dark" : ""}>
            <Head>
                <title>Nextjs Portfolio</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
                <link rel="preconnect" href="https://fonts.googleapis.com" />
                <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
                <link href="https://fonts.googleapis.com/css2?family=Leckerli+One&display=swap" rel="stylesheet" />
            </Head>

            <main className='text-black bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900'>
                <section className='min-h-screen'>
                    <nav className='py-10 mb-12 flex justify-between'>
                        <h1 className='logo-mine font-bold bg-teal-500 '>
                            <a href="#" className='dark:text-gray-600' >HKRY</a>
                        </h1>

                        <ul className='flex items-center'>
                            <li><BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)} className='cursor-pointer text-2xl text-gray-300 dark:text-gray-600' /></li>
                            <li><a className='bg-gradient-to-r from-cyan-500 to-teal-500 dark:text-gray-600 font-semibold text-white px-4 py-2 rounded-md ml-8' href="#">Resume</a></li>
                        </ul>
                    </nav>

                    <div className='text-center p-10'>
                        <h2 className='text-5xl text-teal-600 font-medium md:text-6xl'>Hasan Kuray</h2>
                        <h3 className='text-2xl py-2 md:text-3xl dark:text-white'>Jr. Frontend Developer</h3>
                        <p className='text-md leading-8 text-gray-800 md:text-xl max-w-lg mx-auto dark:text-gray-300'>
                            A software developer trying to improve himself in the frontend field.
                        </p>
                    </div>

                    <div className='text-5xl flex justify-center gap-16 py-3 text-gray-600'>
                        <AiFillTwitterCircle />
                        <AiFillYoutube />
                        <AiFillLinkedin />
                    </div>

                    <div className='relative bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 mx-auto overflow-hidden md:h-96 md:w-96'>
                        <Image src={deved} fill className='object-cover' alt='deved' />
                    </div>
                </section>


                <section className='mt-10'>
                    <div>
                        <h3 className='text-3xl py-1 dark:text-white'>Services I offer</h3>
                        <p className='text-md py-2 leading-8 text-gray-800 dark:text-gray-300'>
                            Since beginning of my joourney as a freelance developer, I&apos;ve done remote work for
                            <span className='text-teal-500'> agencies</span> consulted for <span className='text-teal-500'>startups</span> and collaborated with talented
                            people to create digital for both business and consumer use.
                        </p>
                        <p className='text-md py-2 leading-8 text-gray-800 dark:text-gray-300'>
                            I offer from a wide range of services, including brand developer, programming and teaching.
                        </p>
                    </div>

                    <div className='lg:flex lg:gap-10'>
                        <div className='flex flex-col items-center shadow-lg p-10 rounded-xl my-10 shadow-black dark:bg-white'>
                            <Image src={design} width={100} height={100} alt="design" />
                            <h3 className='text-lg font-medium pt-8 pb-2'>Beautiful Designs</h3>
                            <p>
                                Creating elegant designs suited for your needs following core design theory.
                            </p>
                            <h4 className='py-4 text-teal-600'>Design Tools I Use</h4>
                            <p className='text-gray-800 py-1'>Photoshop</p>
                            <p className='text-gray-800 py-1'>Illustrator</p>
                            <p className='text-gray-800 py-1'>Figma</p>
                        </div>

                        <div className='flex flex-col items-center shadow-lg p-10 rounded-xl my-10 shadow-black dark:bg-white'>
                            <Image src={consulting} width={100} height={100} alt="consulting" />
                            <h3 className='text-lg font-medium pt-8 pb-2'>Beautiful Designs</h3>
                            <p>
                                Creating elegant designs suited for your needs following core design theory.
                            </p>
                            <h4 className='py-4 text-teal-600'>Design Tools I Use</h4>
                            <p className='text-gray-800 py-1'>Photoshop</p>
                            <p className='text-gray-800 py-1'>Illustrator</p>
                            <p className='text-gray-800 py-1'>Figma</p>
                        </div>

                        <div className='flex flex-col items-center shadow-lg p-10 rounded-xl my-10 shadow-black dark:bg-white'>
                            <Image src={code} width={100} height={100} alt="code" />
                            <h3 className='text-lg font-medium pt-8 pb-2'>Beautiful Designs</h3>
                            <p>
                                Creating elegant designs suited for your needs following core design theory.
                            </p>
                            <h4 className='py-4 text-teal-600'>Design Tools I Use</h4>
                            <p className='text-gray-800 py-1'>Photoshop</p>
                            <p className='text-gray-800 py-1'>Illustrator</p>
                            <p className='text-gray-800 py-1'>Figma</p>
                        </div>
                    </div>
                </section>

                <section>
                    <div>
                        <h3 className='text-3xl py-1 dark:text-white'>Portfolio</h3>
                        <p className='text-md py-2 leading-8 text-gray-800 dark:text-gray-300'>
                            Since beginning of my joourney as a freelance developer, I&apos;ve done remote work for
                            <span className='text-teal-500'> agencies</span> consulted for <span className='text-teal-500'>startups</span> and collaborated with talented
                            people to create digital for both business and consumer use.
                        </p>
                        <p className='text-md py-2 leading-8 text-gray-800 dark:text-gray-300'>
                            I offer from a wide range of services, including brand developer, programming and teaching.
                        </p>
                    </div>

                    <div className='flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap'>
                        <div className='basis-1/3 flex-1'>
                            <Image src={web1} className="rounded-lg w-full h-full" alt='web1' />
                        </div>
                        <div className='basis-1/3 flex-1'>
                            <Image src={web2} className="rounded-lg w-full h-full" alt='web2' />
                        </div>
                        <div className='basis-1/3 flex-1'>
                            <Image src={web3} className="rounded-lg w-full h-full" alt='web3'/>
                        </div>
                        <div className='basis-1/3 flex-1'>
                            <Image src={web4} className="rounded-lg w-full h-full" alt='web4'/>
                        </div>
                        <div className='basis-1/3 flex-1'>
                            <Image src={web5} className="rounded-lg w-full h-full" alt='web5'/>
                        </div>
                        <div className='basis-1/3 flex-1'>
                            <Image src={web6} className="rounded-lg w-full h-full" alt='web6'/>
                        </div>
                    </div>
                </section>
            </main>
        </div>
    )
}
